import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const srcDir = path.join(root, 'src');
const distDir = path.join(root, 'dist');
if (!fs.existsSync(distDir)) fs.mkdirSync(distDir, { recursive: true });

// Cascade order matters: base first (resets + keyframes), then components, utilities last.
const ORDER = ['base', 'layout', 'button', 'form', 'disclosure', 'card', 'feedback', 'nav', 'overlay', 'data', 'media', 'mockup', 'utilities'];

let bundle =
  `/**\n` +
  ` * @nekostack/ui — vanilla CSS component library.\n` +
  ` * Generated by build.mjs. Consumes @nekostack/theme tokens (--neko-*).\n` +
  ` * Load AFTER @nekostack/theme's neko.css so the variables resolve.\n` +
  ` */\n`;

const present = [];
const pending = [];
for (const name of ORDER) {
  const f = path.join(srcDir, name + '.css');
  if (fs.existsSync(f)) {
    present.push(name);
    bundle += `\n/* ===================== ${name} ===================== */\n` + fs.readFileSync(f, 'utf8').trimEnd() + '\n';
  } else {
    pending.push(name);
  }
}

fs.writeFileSync(path.join(distDir, 'ui.css'), bundle);

// crude but safe minify
const min = bundle
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/\s+/g, ' ')
  .replace(/\s*([{}:;,>])\s*/g, '$1')
  .replace(/;}/g, '}')
  .trim();
fs.writeFileSync(path.join(distDir, 'ui.min.css'), min);

// component catalog: block-level .neko-<block> selectors (stops before --modifier and __element)
const blocks = new Set();
for (const m of bundle.matchAll(/\.(neko-[a-z0-9]+(?:-[a-z0-9]+)*)(?![\w-])/g)) blocks.add(m[1]);
const catalog = [...blocks].sort();
fs.writeFileSync(path.join(distDir, 'components.json'), JSON.stringify(catalog, null, 2));

// token-purity guard: any hex color outside comments is a violation
const noComments = bundle.replace(/\/\*[\s\S]*?\*\//g, '');
const hexes = [...new Set([...noComments.matchAll(/#[0-9a-fA-F]{3,8}\b/g)].map((m) => m[0]))];

fs.writeFileSync(
  path.join(distDir, 'index.js'),
  `// Generated by build.mjs.\n` +
    `export const cssPath = new URL('./ui.css', import.meta.url).href;\n` +
    `export const components = ${JSON.stringify(catalog)};\n` +
    `export default components;\n`,
);
fs.writeFileSync(
  path.join(distDir, 'index.d.ts'),
  `export declare const cssPath: string;\nexport declare const components: readonly string[];\ndeclare const _default: readonly string[];\nexport default _default;\n`,
);

console.log(`built dist/ui.css (${bundle.length} bytes) + dist/ui.min.css (${min.length} bytes)`);
console.log(`present (${present.length}): ${present.join(', ')}`);
if (pending.length) console.log(`PENDING (${pending.length}): ${pending.join(', ')}`);
console.log(`components (${catalog.length}): ${catalog.join(', ')}`);
if (hexes.length) console.log(`TOKEN-PURITY FAIL — ${hexes.length} hardcoded color(s): ${hexes.join(', ')}`);
else console.log('token-purity: OK (zero hardcoded hex colors)');
