/**
 * Provenance parser for `*.migration.ts` files (v0.8 Step 2).
 *
 * Reads the migration-header metadata out of an authored migration
 * file so `buildMigrationRegistry` can index by
 * `(schemaId, fromVersion, toVersion)` and `verifyMigrationProvenance`
 * can compare the recorded hashes against the current schema
 * registry. Migration files use **JSDoc-only** carriers — there is
 * no JSON variant because migrations are TypeScript modules, not
 * data documents.
 *
 * Expected header shape (generated by the v0.8 stub generator;
 * humans edit the body, not the header):
 *
 *     /**
 *      * @migration by @nekostack/schema
 *      * schemaId:         com.x.User
 *      * fromVersion:      1.0.0
 *      * toVersion:        2.0.0
 *      * fromIrHash:       sha256:<64-hex>
 *      * toIrHash:         sha256:<64-hex>
 *      * fromSourceHash:   sha256:<64-hex>
 *      * toSourceHash:     sha256:<64-hex>
 *      * generator:        neko-schema-migrate-stub
 *      * generatorVersion: @nekostack/schema@0.8.0
 *      *
 *      * DO NOT REMOVE THE HEADER. Authors EDIT THE BODY.
 *      * /
 *
 * The function is **pure**: no `fs.*`, no `import()`, no path
 * argument, no module evaluation. The CLI reads the migration file
 * text from disk and hands it in; this module parses and returns.
 * Master plan Decision #1 boundary applies.
 *
 * **Fail-loud, never silent** (v0.8 Round-2 lock — intentional
 * departure from v0.7 Decision #5). A `.migration.ts` file exists
 * specifically to declare a `(schemaId, fromVersion, toVersion)`
 * transition. Missing or malformed provenance is treated as an
 * invalid declaration, not a "skip and continue" condition.
 * Malformed input surfaces as `Result<...>` failure with one
 * `integrity_error` `Issue` whose `metadata.reason` records the
 * sub-mode (`missing_migration_provenance`, `missing_field`,
 * `malformed_hash`, `malformed_field`, `unknown_format`).
 *
 * The shape of `reason` deliberately overlaps with the v0.7
 * provenance-parser reasons where the failure mode is the same —
 * a missing JSDoc block reads identically in both worlds, so
 * `missing_provenance` would have worked, but the migration-specific
 * `missing_migration_provenance` name lets downstream consumers
 * disambiguate without parsing `message`.
 */

import type { Issue, Result } from "../errors/issue.js";

const SHA256_PATTERN = /^sha256:[0-9a-f]{64}$/;

/**
 * Parsed migration provenance fields. All fields are required —
 * unlike v0.7's `ParsedProvenance` which tolerates v0.6-era artifacts
 * missing `sourceHash`, the migration carrier has no backward-
 * compatibility window. v0.8 is the first phase that emits migration
 * files; every header it emits carries all four hashes.
 */
export interface ParsedMigrationProvenance {
  readonly generator: string;
  readonly generatorVersion: string;
  readonly schemaId: string;
  readonly fromVersion: string;
  readonly toVersion: string;
  readonly fromIrHash: `sha256:${string}`;
  readonly toIrHash: `sha256:${string}`;
  readonly fromSourceHash: `sha256:${string}`;
  readonly toSourceHash: `sha256:${string}`;
}

/**
 * Parse the migration JSDoc header out of a migration file's text
 * content. Returns `Result.success` with the parsed fields on a
 * valid header, `Result.failure` with an `integrity_error` `Issue`
 * on every failure mode.
 */
export function parseMigrationProvenanceFromText(
  content: string,
): Result<ParsedMigrationProvenance> {
  const trimmed = content.trimStart();
  if (!trimmed.startsWith("/**")) {
    return fail(
      "unknown_format",
      "Migration file does not start with a `/** ... */` JSDoc header.",
    );
  }
  return parseJsdocHeader(content);
}

// =============================================================================
// JSDoc header parsing
// =============================================================================

const JSDOC_BLOCK = /\/\*\*([\s\S]*?)\*\//;
const JSDOC_FIELD = /^\s*\*\s+(\w+):\s*(.+?)\s*$/;

function parseJsdocHeader(
  content: string,
): Result<ParsedMigrationProvenance> {
  const block = JSDOC_BLOCK.exec(content);
  if (!block) {
    return fail(
      "missing_migration_provenance",
      "No `/** ... */` JSDoc header found at the top of the migration file.",
    );
  }
  const fields = new Map<string, string>();
  for (const line of block[1]!.split(/\r?\n/)) {
    const m = JSDOC_FIELD.exec(line);
    if (!m) continue;
    fields.set(m[1]!, m[2]!);
  }
  return assembleMigrationProvenance(fields);
}

// =============================================================================
// Field assembly + validation
// =============================================================================

const REQUIRED_FIELDS = [
  "generator",
  "generatorVersion",
  "schemaId",
  "fromVersion",
  "toVersion",
  "fromIrHash",
  "toIrHash",
  "fromSourceHash",
  "toSourceHash",
] as const;

const HASH_FIELDS = [
  "fromIrHash",
  "toIrHash",
  "fromSourceHash",
  "toSourceHash",
] as const;

function assembleMigrationProvenance(
  fields: Map<string, string>,
): Result<ParsedMigrationProvenance> {
  // 1. Every required field must be present.
  for (const name of REQUIRED_FIELDS) {
    if (fields.get(name) === undefined) {
      return fail(
        "missing_field",
        `Migration provenance is missing required field \`${name}\`.`,
      );
    }
  }

  // 2. String-shape fields must be non-empty (the JSDoc regex
  //    already rejects whitespace-only values, but an empty value
  //    after a colon could still slip through on a malformed line —
  //    treat that as `malformed_field`).
  for (const name of REQUIRED_FIELDS) {
    const value = fields.get(name)!;
    if (value.length === 0) {
      return fail(
        "malformed_field",
        `Migration provenance field \`${name}\` is empty.`,
      );
    }
  }

  // 3. Every hash field must match the sha256 shape.
  for (const name of HASH_FIELDS) {
    const value = fields.get(name)!;
    if (!SHA256_PATTERN.test(value)) {
      return fail(
        "malformed_hash",
        `Migration provenance \`${name}\` must match \`sha256:<64 hex>\`; got "${value}".`,
      );
    }
  }

  return {
    success: true,
    data: {
      generator: fields.get("generator")!,
      generatorVersion: fields.get("generatorVersion")!,
      schemaId: fields.get("schemaId")!,
      fromVersion: fields.get("fromVersion")!,
      toVersion: fields.get("toVersion")!,
      fromIrHash: fields.get("fromIrHash")! as `sha256:${string}`,
      toIrHash: fields.get("toIrHash")! as `sha256:${string}`,
      fromSourceHash: fields.get("fromSourceHash")! as `sha256:${string}`,
      toSourceHash: fields.get("toSourceHash")! as `sha256:${string}`,
    },
  };
}

// =============================================================================
// Failure helper
// =============================================================================

function fail(
  reason: string,
  message: string,
): Result<ParsedMigrationProvenance> {
  const issue: Issue = {
    code: "integrity_error",
    path: [],
    message,
    severity: "error",
    metadata: { reason },
  };
  return { success: false, issues: [issue] };
}
