/**
 * `stubMigration(opts)` — pure migration-stub generator (v0.8 Step 6).
 *
 * Produces a `MigrationStub` payload — a `suggestedPath` and the
 * full file `content` for a new `*.migration.ts` file. The CLI is
 * responsible for actually writing the file; this primitive is
 * pure (no `fs.*`, no `import()`, no `process.*`, no `console.*`).
 *
 * The content follows the locked migration shape (Decision #5 +
 * Decision #6):
 *
 *   - JSDoc provenance header on top, generated by this function.
 *   - `import type { Migration } from "@nekostack/schema/cli";`
 *     (NOT root — Decision #6 keeps the v0.8 surface package-internal).
 *   - A `const migration: Migration<schemaId, from, to> = { ... }`
 *     with a skeleton `transform` that throws "Not yet implemented".
 *     Authors edit the body; v0.8 never invokes `transform`.
 *   - `export default migration;` so `buildMigrationRegistry` /
 *     `verifyMigrationProvenance` can find it via the
 *     `MigrationSourceEntry.migration` field.
 *
 * `suggestedPath` follows the locked path convention
 * (Decision #5):
 *
 *   <schema-dir>/migrations/<basename>.<from-slug>-to-<to-slug>.migration.ts
 *
 * with the slug rule reused verbatim from `v0.7 src/registry/handlers/generate.ts`:
 *   `lowercase → non-alphanumeric runs collapse to "-" → trim`.
 *
 * Reusing v0.7's `slugify` shape means one slug rule across the
 * whole package — and it handles prerelease/build version markers
 * (`1.0.0-beta.1`, `2.0.0+build.5`) cleanly.
 *
 * Failure path: if either operand version is absent from the schema
 * registry → `Result.failure` with `migration_missing_endpoint`
 * (same code as Step 4's planner uses for the same condition).
 */

import { findSchema } from "../registry/build-registry.js";
import { GENERATOR_VERSION } from "../generators/version.js";
import type { Issue, Result } from "../errors/issue.js";
import type {
  MigrationStub,
  MigrationStubOpts,
  MigrationStubResult,
} from "./types.js";

// =============================================================================
// Public entry
// =============================================================================

export function stubMigration(
  opts: MigrationStubOpts,
): MigrationStubResult {
  const fromEntry = findSchema(opts.schemaRegistry, opts.schemaId, opts.fromVersion);
  const toEntry = findSchema(opts.schemaRegistry, opts.schemaId, opts.toVersion);

  if (fromEntry === undefined || toEntry === undefined) {
    return failure(
      missingEndpointIssue(
        opts.schemaId,
        opts.fromVersion,
        opts.toVersion,
        fromEntry === undefined,
        toEntry === undefined,
      ),
    );
  }

  const suggestedPath = suggestedMigrationPathFor(
    fromEntry.sourcePath,
    opts.fromVersion,
    opts.toVersion,
  );
  const content = renderStubContent({
    schemaId: opts.schemaId,
    fromVersion: opts.fromVersion,
    toVersion: opts.toVersion,
    fromIrHash: fromEntry.irHash,
    toIrHash: toEntry.irHash,
    fromSourceHash: fromEntry.sourceHash,
    toSourceHash: toEntry.sourceHash,
  });

  const stub: MigrationStub = {
    schemaId: opts.schemaId,
    fromVersion: opts.fromVersion,
    toVersion: opts.toVersion,
    suggestedPath,
    content,
  };
  return { success: true, data: stub };
}

// =============================================================================
// Path convention (Decision #5)
// =============================================================================

/**
 * Translate a schema's `sourcePath` plus a version pair into the
 * locked migration-file path:
 *
 *     <schema-dir>/migrations/<basename>.<from-slug>-to-<to-slug>.migration.ts
 *
 * `basename` strips a `.schema.{ts,js,mts,cts}` suffix when present;
 * falls back to "filename minus last extension" otherwise. Forward
 * slashes are canonical even on Windows — the CLI normalizes back
 * to platform separators on write.
 *
 * Exported so the CLI's `stub` verb can advertise the same path
 * without re-deriving the rule.
 */
export function suggestedMigrationPathFor(
  sourcePath: string,
  fromVersion: string,
  toVersion: string,
): string {
  const normalized = sourcePath.replace(/\\/g, "/");
  const lastSlash = normalized.lastIndexOf("/");
  const dir = lastSlash >= 0 ? normalized.slice(0, lastSlash) : "";
  const filename =
    lastSlash >= 0 ? normalized.slice(lastSlash + 1) : normalized;
  const basename = basenameOf(filename);
  const stem = `${basename}.${slugify(fromVersion)}-to-${slugify(toVersion)}`;
  const migrationsDir = dir === "" ? "migrations" : `${dir}/migrations`;
  return `${migrationsDir}/${stem}.migration.ts`;
}

function basenameOf(filename: string): string {
  const schemaMatch = filename.match(/^(.+?)\.schema\.(ts|js|mts|cts)$/);
  if (schemaMatch) return schemaMatch[1]!;
  const lastDot = filename.lastIndexOf(".");
  return lastDot > 0 ? filename.slice(0, lastDot) : filename;
}

/**
 * Same shape as v0.7's `src/registry/handlers/generate.ts` slugify().
 * One slug rule across the whole package — Round-2 lock.
 */
function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// =============================================================================
// Content rendering
// =============================================================================

interface RenderInput {
  readonly schemaId: string;
  readonly fromVersion: string;
  readonly toVersion: string;
  readonly fromIrHash: `sha256:${string}`;
  readonly toIrHash: `sha256:${string}`;
  readonly fromSourceHash: `sha256:${string}`;
  readonly toSourceHash: `sha256:${string}`;
}

function renderStubContent(input: RenderInput): string {
  // Pad keys to 16 columns so the value column lines up visually,
  // matching the v0.7 generator-header convention. The parser is
  // whitespace-tolerant so consumers may edit the alignment without
  // breaking provenance reads.
  const header = renderHeader({
    schemaId: input.schemaId,
    fromVersion: input.fromVersion,
    toVersion: input.toVersion,
    fromIrHash: input.fromIrHash,
    toIrHash: input.toIrHash,
    fromSourceHash: input.fromSourceHash,
    toSourceHash: input.toSourceHash,
    generator: "neko-schema-migrate-stub",
    generatorVersion: GENERATOR_VERSION,
  });
  const literalSchemaId = JSON.stringify(input.schemaId);
  const literalFrom = JSON.stringify(input.fromVersion);
  const literalTo = JSON.stringify(input.toVersion);
  return `${header}
import type { Migration } from "@nekostack/schema/cli";

const migration: Migration<${literalSchemaId}, ${literalFrom}, ${literalTo}> = {
  schemaId: ${literalSchemaId},
  from: ${literalFrom},
  to: ${literalTo},
  transform(input) {
    // Author fills this in.
    throw new Error("Not yet implemented");
  },
};

export default migration;
`;
}

function renderHeader(
  fields: Record<string, string>,
): string {
  const keys = [
    "schemaId",
    "fromVersion",
    "toVersion",
    "fromIrHash",
    "toIrHash",
    "fromSourceHash",
    "toSourceHash",
    "generator",
    "generatorVersion",
  ] as const;
  const colon = ":";
  const targetWidth = Math.max(...keys.map((k) => k.length + colon.length));
  const lines = [
    "/**",
    " * @migration by @nekostack/schema",
    ...keys.map((k) => {
      const label = `${k}${colon}`;
      return ` * ${label.padEnd(targetWidth + 1)}${fields[k]}`;
    }),
    " *",
    " * DO NOT REMOVE THE HEADER. Authors EDIT THE BODY.",
    " */",
  ];
  return lines.join("\n");
}

// =============================================================================
// Failure helpers
// =============================================================================

function failure(issue: Issue): MigrationStubResult {
  return { success: false, issues: [issue] };
}

function missingEndpointIssue(
  schemaId: string,
  fromVersion: string,
  toVersion: string,
  fromMissing: boolean,
  toMissing: boolean,
): Issue {
  const missing: string[] = [];
  if (fromMissing) missing.push("from");
  if (toMissing) missing.push("to");
  return {
    code: "migration_missing_endpoint",
    path: [],
    message:
      `Cannot stub migration for \`${schemaId}\`: ` +
      `${missing.join(", ")} version not in the schema registry ` +
      `(from=${fromVersion}, to=${toVersion}).`,
    severity: "error",
    metadata: {
      schemaId,
      fromVersion,
      toVersion,
      missing,
    },
  };
}
