import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');
const srcPath = path.join(rootDir, 'src', 'tokens.json');
const distDir = path.join(rootDir, 'dist');

if (!fs.existsSync(distDir)) fs.mkdirSync(distDir, { recursive: true });
const tokensRaw = JSON.parse(fs.readFileSync(srcPath, 'utf8'));

if (!tokensRaw.base || typeof tokensRaw.base !== 'object') {
  console.error("❌ Critical Error: tokens.json is missing a 'base' object.");
  process.exit(1);
}
if (!tokensRaw.themes || typeof tokensRaw.themes !== 'object') {
  console.error("❌ Critical Error: tokens.json is missing a 'themes' object.");
  process.exit(1);
}
if (Object.keys(tokensRaw.themes).length === 0) {
  console.error("❌ Critical Error: 'themes' in tokens.json is empty.");
  process.exit(1);
}

function resolveValue(val, root) {
  // If it's a DTCG object, extract the value first. We check for 'value' in val.
  const v = (val !== null && typeof val === 'object' && 'value' in val) ? val.value : val;

  if (typeof v === 'string' && v.startsWith('{') && v.endsWith('}')) {
    const pathStr = v.slice(1, -1);
    const resolved = pathStr.split('.').reduce((acc, curr) => acc?.[curr], root);
    if (resolved === undefined) {
      console.error(`❌ Critical Error: Could not resolve alias "${v}"`);
      process.exit(1);
    }
    return resolveValue(resolved, root);
  }
  return v;
}

function resolveTokens(obj, root) {
  if (obj !== null && typeof obj === 'object' && !Array.isArray(obj)) {
    if ('value' in obj) {
      return { ...obj, value: resolveValue(obj, root) };
    }
    const out = {};
    for (const [k, v] of Object.entries(obj)) out[k] = resolveTokens(v, root);
    return out;
  }
  return obj;
}

const tokens = resolveTokens(tokensRaw, tokensRaw);

const defaultTheme = tokens.meta?.default_theme ?? Object.keys(tokens.themes)[0];
const defaultMode = tokens.meta?.default_mode ?? Object.keys(tokens.themes[defaultTheme].modes)[0];

function flatten(obj, prefix = '') {
  const out = {};
  (function recurse(current, p) {
    for (const [k, v] of Object.entries(current)) {
      const np = p ? `${p}-${k}` : k;
      if (v !== null && typeof v === 'object' && !Array.isArray(v)) {
        if ('value' in v) out[np] = v.value;
        else recurse(v, np);
      } else {
        out[np] = v;
      }
    }
  })(obj, prefix);
  return out;
}

function emitBlock(selector, vars, indent = '  ') {
  let s = `${selector} {\n`;
  for (const [name, val] of Object.entries(vars)) s += `${indent}--${name}: ${val};\n`;
  s += `}\n\n`;
  return s;
}

// ---------------- 1. dist/neko.css ----------------
// :root carries the theme-invariant base AND the default (theme, mode) — so a
// page with no data-theme/data-mode renders correctly. Every other (theme, mode)
// gets its own selector block. Partial-attribute conveniences are also emitted.

let css =
  `/**\n` +
  ` * @nekostack/theme — generated by build.mjs. Do not edit.\n` +
  ` *\n` +
  ` * Defaults: theme="${defaultTheme}", mode="${defaultMode}".\n` +
  ` *   <html>                                            → ${defaultTheme} · ${defaultMode}\n` +
  ` *   <html data-theme="X">                             → X · ${defaultMode}\n` +
  ` *   <html data-mode="Y">                              → ${defaultTheme} · Y\n` +
  ` *   <html data-theme="X" data-mode="Y">               → X · Y\n` +
  ` *\n` +
  ` * Themes live under tokens.themes.<name>; modes under .modes.<dark|light>.\n` +
  ` * Components consume only semantic role tokens (--neko-color-semantic-*).\n` +
  ` */\n\n`;

// :root = base + default theme + default mode
const baseVars = flatten(tokens.base, 'neko');
const defaultThemeData = tokens.themes[defaultTheme].modes[defaultMode];
const defaultThemeVars = flatten(defaultThemeData, 'neko');
css += emitBlock(':root', { ...baseVars, ...defaultThemeVars });

// color-scheme declarations so native controls (select dropdowns, scrollbars) match the mode
css += `/* color-scheme — tells browsers how to render native form controls */\n`;
css += `:root { color-scheme: ${defaultMode}; }\n`;
css += `[data-mode="dark"] { color-scheme: dark; }\n`;
css += `[data-mode="light"] { color-scheme: light; }\n\n`;

// every (theme, mode) combination
const themeNames = Object.keys(tokens.themes);
for (const themeName of themeNames) {
  const themeData = tokens.themes[themeName];
  const modeNames = Object.keys(themeData.modes);
  for (const modeName of modeNames) {
    if (themeName === defaultTheme && modeName === defaultMode) continue;
    const vars = flatten(themeData.modes[modeName], 'neko');

    const selectors = [`[data-theme="${themeName}"][data-mode="${modeName}"]`];
    if (themeName === defaultTheme && modeName !== defaultMode) {
      // only data-mode is set → use default theme + this mode
      selectors.push(`:not([data-theme])[data-mode="${modeName}"]`);
    }
    if (modeName === defaultMode && themeName !== defaultTheme) {
      // only data-theme is set → use this theme + default mode
      selectors.push(`[data-theme="${themeName}"]:not([data-mode])`);
    }
    css += emitBlock(selectors.join(',\n'), vars);
  }
}

// reduced motion (theme-invariant)
if (tokens['reduced-motion']) {
  const motionVars = flatten(tokens['reduced-motion'], 'neko');
  css += `@media (prefers-reduced-motion: reduce) {\n`;
  css += `  :root {\n`;
  for (const [k, v] of Object.entries(motionVars)) css += `    --${k}: ${v};\n`;
  css += `  }\n}\n\n`;
  css += emitBlock('[data-motion="reduce"]', motionVars);
}

fs.writeFileSync(path.join(distDir, 'neko.css'), css);

// ---------------- 2. dist/tokens.json (passthrough) ----------------
fs.writeFileSync(path.join(distDir, 'tokens.json'), JSON.stringify(tokens, null, 2));

// ---------------- 3. dist/tokens.js + tokens.d.ts (ESM) ----------------
const tokensLiteral = JSON.stringify(tokens, null, 2);
const themeOptions = themeNames.flatMap((t) =>
  Object.keys(tokens.themes[t].modes).map((m) => ({
    theme: t,
    mode: m,
    label: `${tokens.themes[t].label ?? t} · ${m[0].toUpperCase() + m.slice(1)}`,
    isDefault: t === defaultTheme && m === defaultMode,
  })),
);

fs.writeFileSync(
  path.join(distDir, 'tokens.js'),
  `// Generated by build.mjs. Do not edit.\n` +
    `export const tokens = ${tokensLiteral};\n` +
    `export const defaultTheme = ${JSON.stringify(defaultTheme)};\n` +
    `export const defaultMode = ${JSON.stringify(defaultMode)};\n` +
    `export const themeOptions = ${JSON.stringify(themeOptions, null, 2)};\n` +
    `export default tokens;\n`,
);
fs.writeFileSync(
  path.join(distDir, 'tokens.d.ts'),
  `// Generated by build.mjs.\n` +
    `export type NekoSemanticColorToken = \`--neko-color-semantic-\${string}\`;\n` +
    `export type NekoToken = \`--neko-\${string}\`;\n` +
    `export type TokenValue = string | number;\n` +
    `export declare const tokens: ${tokensLiteral} & Record<string, unknown>;\n` +
    `export declare const defaultTheme: string;\n` +
    `export declare const defaultMode: string;\n` +
    `export declare const themeOptions: ReadonlyArray<{ theme: string; mode: string; label: string; isDefault: boolean }>;\n` +
    `export type Tokens = typeof tokens;\n` +
    `declare const _default: typeof tokens;\nexport default _default;\n`,
);

// ---------------- 4. dist/index.js + index.d.ts ----------------
fs.writeFileSync(
  path.join(distDir, 'index.js'),
  `export { tokens, defaultTheme, defaultMode, themeOptions, default } from './tokens.js';\nexport * from './tokens.js';\n`,
);
fs.writeFileSync(
  path.join(distDir, 'index.d.ts'),
  `export { tokens, defaultTheme, defaultMode, themeOptions, default, type Tokens } from './tokens.js';\n`,
);

// ---------------- 5. dist/tokens-window.js (classic script for preview.html) ----------------
fs.writeFileSync(
  path.join(distDir, 'tokens-window.js'),
  `/* Generated by build.mjs — classic script (works over file://). */\n` +
    `window.NEKO_TOKENS = ${tokensLiteral};\n` +
    `window.NEKO_DEFAULT_THEME = ${JSON.stringify(defaultTheme)};\n` +
    `window.NEKO_DEFAULT_MODE = ${JSON.stringify(defaultMode)};\n` +
    `window.NEKO_THEME_OPTIONS = ${JSON.stringify(themeOptions)};\n`,
);

// ---------------- 6. dist/tailwind.preset.cjs ----------------
function toVars(obj, p = 'neko') {
  const r = {};
  for (const [k, v] of Object.entries(obj)) {
    const np = `${p}-${k}`;
    if (v !== null && typeof v === 'object' && !Array.isArray(v)) {
      if ('value' in v) r[k] = `var(--${np})`;
      else r[k] = toVars(v, np);
    } else {
      r[k] = `var(--${np})`;
    }
  }
  return r;
}
// Tailwind preset maps to the default-theme/default-mode semantic vars (correct since they
// resolve to whatever theme is active via CSS variables at runtime).
const mergedForTw = { ...tokens.base, color: { ...tokens.base.color, semantic: tokens.themes[defaultTheme].modes[defaultMode].color.semantic } };
const mapped = toVars(mergedForTw, 'neko');
const preset = {
  theme: {
    extend: {
      colors: mapped.color || {},
      spacing: mapped.spacing || {},
      borderRadius: mapped.radius || {},
      fontFamily: mapped.font || {},
      fontSize: mapped['font-size'] || {},
      lineHeight: mapped['line-height'] || {},
      transitionDuration: mapped.motion?.duration || {},
      transitionTimingFunction: mapped.motion?.easing || {},
      zIndex: mapped['z-index'] || {},
      boxShadow: mapped.color?.shadow || {},
    },
  },
};
fs.writeFileSync(
  path.join(distDir, 'tailwind.preset.cjs'),
  `/**\n * @nekostack/theme — Tailwind preset. Generated by build.mjs.\n * @type {import('tailwindcss').Config}\n */\nmodule.exports = ${JSON.stringify(preset, null, 2)};\n`,
);

console.log('built:');
for (const f of [
  'neko.css', 'tokens.json', 'tokens.js', 'tokens.d.ts',
  'index.js', 'index.d.ts', 'tokens-window.js', 'tailwind.preset.cjs',
]) console.log('  dist/' + f);
console.log('themes × modes:');
for (const o of themeOptions) console.log(`  ${o.label}${o.isDefault ? '  (default)' : ''}`);
