import type { SchemaNode } from "../ir/nodes.js";
import { irHash } from "../ir/hash.js";
import { GENERATOR_VERSION } from "./version.js";

export interface HeaderOptions {
  /** Which generator emitted this file. Affects the header's `generator` field. */
  generator: "typescript" | "zod";
  /** Optional override for the schema-version field, when no `metadata.version` is set on the node. */
  schemaVersion?: string;
}

/**
 * Build the deterministic JSDoc block prepended to every generated file.
 *
 * Fields (one per line, no `sourceHash` in v0.2 — that requires the CLI to
 * walk source files and is deferred to v0.7):
 *
 *   @generated by @nekostack/schema
 *   schemaId:        <metadata.id or "anonymous">
 *   schemaVersion:   <metadata.version or "unversioned">
 *   irHash:          sha256:<hex>
 *   generator:       <typescript|zod>
 *   generatorVersion: <package version string>
 *
 *   DO NOT EDIT MANUALLY.
 *
 * Determinism: same IR + same generator version → byte-identical header.
 * Anonymous schemas (no `.id()`) emit `schemaId: null` and include a
 * `// anonymous schema` comment so the omission is intentional and visible.
 */
export function buildHeader(node: SchemaNode, options: HeaderOptions): string {
  const id = node.metadata?.id ?? null;
  const version = node.metadata?.version ?? options.schemaVersion ?? null;
  const hash = irHash(node);

  const lines: string[] = [
    "/**",
    " * @generated by @nekostack/schema",
  ];
  if (id === null) {
    lines.push(" * // anonymous schema");
  }
  lines.push(
    ` * schemaId:         ${id === null ? "null" : id}`,
    ` * schemaVersion:    ${version === null ? "null" : version}`,
    ` * irHash:           sha256:${hash}`,
    ` * generator:        ${options.generator}`,
    ` * generatorVersion: ${GENERATOR_VERSION}`,
    " *",
    " * DO NOT EDIT MANUALLY.",
    " */",
  );
  return lines.join("\n");
}
