import type { SchemaNode } from "../ir/nodes.js";
import { irHash } from "../ir/hash.js";
import { GENERATOR_VERSION } from "./version.js";

export interface HeaderOptions {
  /** Which generator emitted this file. Affects the header's `generator` field. */
  generator: "typescript" | "zod";
  /** Optional override for the schema-version field, when no `metadata.version` is set on the node. */
  schemaVersion?: string;
  /**
   * Optional sha256 of the originating `*.schema.ts` source bytes
   * (`registry/source-hash.ts → sourceHashFromText`). When provided,
   * emitted as a `sourceHash:` line between `irHash:` and `generator:`.
   * When omitted, the line is **absent entirely** (Master plan Decision #8;
   * NOT emitted as `null` — older parsers and direct generator callers
   * see a header indistinguishable from the v0.2–v0.6 shape).
   *
   * The CLI (v0.7+, `neko schema *`) passes this through; direct
   * generator calls (vitest snapshots, ad-hoc scripts) omit it so
   * existing snapshots remain byte-identical.
   */
  sourceHash?: `sha256:${string}`;
}

/**
 * Build the deterministic JSDoc block prepended to every generated file.
 *
 * Fields (one per line):
 *
 *   @generated by @nekostack/schema
 *   schemaId:         <metadata.id, or `null` for anonymous schemas>
 *   schemaVersion:    <metadata.version, or `null` for unversioned schemas>
 *   irHash:           sha256:<hex>
 *   [sourceHash:      sha256:<hex>]   ← v0.7+, only when options.sourceHash is set
 *   generator:        <typescript|zod>
 *   generatorVersion: <package version string>
 *
 *   DO NOT EDIT MANUALLY.
 *
 * Determinism: same IR + same generator version + same sourceHash (or
 * same absence) → byte-identical header. Anonymous schemas (no
 * `.id()`) emit `schemaId: null` and include a `// anonymous schema`
 * comment so the omission is intentional and visible.
 */
export function buildHeader(node: SchemaNode, options: HeaderOptions): string {
  const id = node.metadata?.id ?? null;
  const version = node.metadata?.version ?? options.schemaVersion ?? null;
  const hash = irHash(node);

  const lines: string[] = [
    "/**",
    " * @generated by @nekostack/schema",
  ];
  if (id === null) {
    lines.push(" * // anonymous schema");
  }
  lines.push(
    ` * schemaId:         ${id === null ? "null" : id}`,
    ` * schemaVersion:    ${version === null ? "null" : version}`,
    ` * irHash:           sha256:${hash}`,
  );
  if (options.sourceHash !== undefined) {
    // 11 chars "sourceHash:" + 7 spaces to land the value at column 18,
    // matching the existing field-name column width.
    lines.push(` * sourceHash:       ${options.sourceHash}`);
  }
  lines.push(
    ` * generator:        ${options.generator}`,
    ` * generatorVersion: ${GENERATOR_VERSION}`,
    " *",
    " * DO NOT EDIT MANUALLY.",
    " */",
  );
  return lines.join("\n");
}
